/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package srvcln;

import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static srvcln.Cln.adresa;

/**
 *
 * @author Gabitza
 */
public class Activitate extends javax.swing.JFrame {

    /**
     * Creates new form Activitate
     */
    static String MyName = null;
    public Activitate(String MyName) {
        initComponents();
        setIcon();
        this.MyName = MyName;
        I_BD bd = null;
        String url = "rmi://" + adresa + ":" + 1099 + "/bd";
        try {
            bd = (I_BD)Naming.lookup(url);
            if (bd.afla_categorie(MyName).equals("Elev")) {
                UseNrDiscutii.setText(bd.nr_discutii(bd.afla_id_elev(MyName)) + "");
                int valoare = bd.durata_totala_elevi(bd.afla_id_elev(MyName));
                if (valoare > 1)
                    UseDurataTotala.setText(valoare + " minute");
                else UseDurataTotala.setText(1 + " minute");
                ArrayList<String> istoric = bd.istoric(bd.afla_id_elev(MyName));
                UseRating.setVisible(true);
                Istoric.setText("Istoric");
                for (  int i = 0; i < istoric.size(); i = i+4 )
                {
                    UseRating.setText( UseRating.getText() + "\n" + "Materie: " + istoric.get(i) + " - Nume: " + istoric.get(i+1) + " - Numar Conversatii: " + istoric.get(i+2) + " - Durata: " + istoric.get(i+3) + " minute \n" );
                }
            } else {
                UseNrDiscutii.setText(bd.nr_discutii_prof(bd.afla_id_prof(MyName)) + "");
                int valoare = bd.durata_totala_prof(bd.afla_id_prof(MyName));
                if (valoare > 1)
                    UseDurataTotala.setText(valoare + " minute");
                else UseDurataTotala.setText(1 + " minute");
                Istoric.setText("Rating");
                UseRating.setVisible(true);
                UseRating.setText(bd.rating(bd.afla_id_prof(MyName)) + " %");
                
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(Activitate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Activitate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(Activitate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Activitate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NrDiscutii = new javax.swing.JLabel();
        DurataTotata = new javax.swing.JLabel();
        UseNrDiscutii = new javax.swing.JTextField();
        Istoric = new javax.swing.JLabel();
        UseDurataTotala = new javax.swing.JTextField();
        UseRating = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(632, 456));
        setMinimumSize(new java.awt.Dimension(632, 456));
        setPreferredSize(new java.awt.Dimension(632, 456));
        getContentPane().setLayout(null);

        NrDiscutii.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        NrDiscutii.setText("Numar discutii:");
        getContentPane().add(NrDiscutii);
        NrDiscutii.setBounds(100, 80, 133, 23);

        DurataTotata.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        DurataTotata.setText("Durata totala:");
        getContentPane().add(DurataTotata);
        DurataTotata.setBounds(320, 80, 133, 22);

        UseNrDiscutii.setEditable(false);
        UseNrDiscutii.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(UseNrDiscutii);
        UseNrDiscutii.setBounds(100, 110, 180, 23);

        Istoric.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Istoric.setText("Istoric:");
        getContentPane().add(Istoric);
        Istoric.setBounds(270, 140, 60, 23);

        UseDurataTotala.setEditable(false);
        UseDurataTotala.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(UseDurataTotala);
        UseDurataTotala.setBounds(320, 110, 180, 27);

        UseRating.setEditable(false);
        UseRating.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(UseRating);
        UseRating.setBounds(100, 170, 420, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srvcln/discution.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 640, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activitate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activitate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activitate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activitate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activitate(MyName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DurataTotata;
    private javax.swing.JLabel Istoric;
    private javax.swing.JLabel NrDiscutii;
    private javax.swing.JTextField UseDurataTotala;
    private javax.swing.JTextField UseNrDiscutii;
    private javax.swing.JTextField UseRating;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Book » Bookmark.png")));
    }
}
